bazireader/apps/accounts/urls.py

from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

from . import views
from .views import accounts

app_name = "accounts"
urlpatterns = [
    path("", accounts, name='accounts'),
    path('accounts/profile', views.ProfileView.as_view(), name = "profile"),
    #path('accounts/result', views.TemplateView.as_view(template_name="accounts/result.html")),

    # Django Auth
    path('accounts/login',
         auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('accounts/logout',
         auth_views.LogoutView.as_view(), name='logout')
]

bazireader/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name = "contact"
urlpatterns = [
    path("", contact, name='contact' )

]

bazireader/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bazireader.apps.public.urls')),
    path('accounts/', include('bazireader.apps.accounts.urls')),
    path('contact/', include('bazireader.apps.contact.urls')),

    #path('about/', views.about, name="about"),
    #path('contact/', views.contact, name="contact"),
    #path('accounts/profile', views.ProfileView.as_view(), name = "profile"),

    # Django Auth
    #path('accounts/login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    #path('accounts/logout', auth_views.LogoutView.as_view(), name='logout')
]

bazireader/apps/contact/models.py
from django.db import models

# Create your models here.

bazireader/apps/models.py
##

bazireader/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Name"}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "Email"}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Message", 'rows': "5"}))


bazireader/apps/accounts/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
import datetime

from .forms import bz_Form
from .models import bz_langit, bz_bumi, bz_story, bz_arti, bz_annual

def accounts(request: HttpRequest) -> HttpResponse:
    langit = bz_langit.objects.all()
    bumi = bz_bumi.objects.all()
    story = bz_story.objects.all()
    arti = bz_arti.objects.all()
    annual = bz_annual.objects.all()

    if request.method == "GET":
        form = bz_Form()
    elif request.method == "POST":
        form = bz_Form(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            gender = form.cleaned_data["gender"]
            day = form.cleaned_data["day"]
            month = form.cleaned_data["month"]
            year = form.cleaned_data["year"]
            hour = form.cleaned_data["hour"]
            min = form.cleaned_data["min"]
            notime = form.cleaned_data["notime"]
            zone = form.cleaned_data["zone"]
            hha = form.cleaned_data['hha']
            dda = form.cleaned_data['dda']
            mma = form.cleaned_data['mma']
            yya = form.cleaned_data['yya']
            hhb = form.cleaned_data['hhb']
            ddb = form.cleaned_data['ddb']
            mmb = form.cleaned_data['mmb']
            yyb = form.cleaned_data['yyb']

            l2a = form.cleaned_data['l2a']
            l1a = form.cleaned_data['l1a']
            l2b = form.cleaned_data['l2b']
            l1b = form.cleaned_data['l1b']

            # put Natasha algorithm here

            ## cari elemen DM
            for item in langit.values('pinyin','elemen'):
                if item['pinyin'] == dda:
                    dm_elemen = item['elemen']

            ## 0. hitung jumlah elemen
            bz_kar = []
            bz_kar.append(hha)
            bz_kar.append(dda)
            bz_kar.append(mma)
            bz_kar.append(yya)
            bz_kar.append(hhb)
            bz_kar.append(ddb)
            bz_kar.append(mmb)
            bz_kar.append(yyb)

            bz_elm = []
            wood = ({"Jia", "Yi", "Yin", "Mao"})
            fire = ({"Bing", "Ding", "Si", "Uu"})
            metal = ({"Geng", "Xin", "Shen", "You"})
            water = ({"Ren", "Gui", "Hai", "Zi"})
            earth = ({"Wu", "Ji", "Chen", "Wei", "Xu", "Chou"})

            for kar in bz_kar:
                if kar in wood:
                    bz_elm.append("kayu")
                elif kar in fire:
                    bz_elm.append("api")
                elif kar in metal:
                    bz_elm.append("logam")
                elif kar in water:
                    bz_elm.append("air")
                elif kar in earth:
                    bz_elm.append("tanah")

            ## 1. kombo langit

            if "Jia" in bz_kar and "Ji" in bz_kar:
                bz_elm[bz_kar.index("Jia")] = "tanah"

            if "Yi" in bz_kar and "Geng" in bz_kar:
                bz_elm[bz_kar.index("Yi")] = "logam"

            if "Bing" in bz_kar and "Xin" in bz_kar:
                bz_elm[bz_kar.index("Xin")] = "air"
                bz_elm[bz_kar.index("Bing")] = "air"

            if "Ding" in bz_kar and "Ren" in bz_kar:
                bz_elm[bz_kar.index("Ding")] = "kayu"
                bz_elm[bz_kar.index("Ren")] = "kayu"

            if "Wu" in bz_kar and "Gui" in bz_kar:
                bz_elm[bz_kar.index("Gui")] = "api"
                bz_elm[bz_kar.index("Wu")] = "api"

            ## 2. transformasi

            if "Uu" in bz_kar and "Wei" in bz_kar:
                bz_elm[bz_kar.index("Wei")] = "api"

            if "Si" in bz_kar and "Shen" in bz_kar:
                bz_elm[bz_kar.index("Si")] = "air"
                bz_elm[bz_kar.index("Shen")] = "air"

            if "Chen" in bz_kar and "You" in bz_kar:
                bz_elm[bz_kar.index("Chen")] = "logam"

            if "Mao" in bz_kar and "Xu" in bz_kar:
                bz_elm[bz_kar.index("Mao")] = "api"
                bz_elm[bz_kar.index("Xu")] = "api"

            if "Yin" in bz_kar and "Hai" in bz_kar:
                bz_elm[bz_kar.index("Hai")] = "kayu"

            if "Chou" in bz_kar and "Zi" in bz_kar:
                bz_elm[bz_kar.index("Chou")] = "tanah"
                bz_elm[bz_kar.index("Zi")] = "tanah"

            ## 3. Combo bumi

            bz_karset = {bz_kar[0]}

            for v in range(1, 8):
                bz_karset.add(bz_kar[v])

            ar = 0
            l = 0
            k = 0
            ap = 0

            # element sets
            air = {"Zi", "Chen", "Shen"}
            logam = {"Chou", "Si", "You"}
            kayu = {"Mao", "Hai", "Wei"}
            api = {"Yin", "Uu", "Xu"}

            for w in air:
                if w in bz_karset:
                    ar = ar + 1

            for x in logam:
                if x in bz_karset:
                    l = l + 1

            for y in kayu:
                if y in bz_karset:
                    k = k + 1

            for z in api:
                if z in bz_karset:
                    ap = ap + 1

            if ar > 1:
                if "Chen" in bz_kar:
                    bz_elm[bz_kar.index("Chen")] = "air"
                if "Shen" in bz_kar:
                    bz_elm[bz_kar.index("Shen")] = "air"

            if l > 1:
                if "Chou" in bz_kar:
                    bz_elm[bz_kar.index("Chou")] = "logam"
                if "Si" in bz_kar:
                    bz_elm[bz_kar.index("Si")] = "logam"

            if k > 1:
                if "Hai" in bz_kar:
                    bz_elm[bz_kar.index("Hai")] = "kayu"
                if "Wei" in bz_kar:
                    bz_elm[bz_kar.index("Wei")] = "kayu"

            if ap > 1:
                if "Yin" in bz_kar:
                    bz_elm[bz_kar.index("Yin")] = "api"
                if "Xu" in bz_kar:
                    bz_elm[bz_kar.index("Xu")] = "api"

            ii = int(zone)
            age = [zone]
            for jj in range (1, 9):
                ii = 10 + ii
                age.append(str(ii))

            tahun = datetime.datetime.now().year
            umur = tahun - int(year)
            #print("umur:", umur)
            #print("age:", age)

            ## 4. Counting elemen

            kayu = 0
            api = 0
            tanah = 0
            logam = 0
            air = 0

            for elm in bz_elm:
                if elm == "kayu":
                    kayu = kayu + 1
                elif elm == "api":
                    api = api + 1
                elif elm == "tanah":
                    tanah = tanah + 1
                elif elm == "logam":
                    logam = logam + 1
                elif elm == "air":
                    air = air + 1

            #print("kayu", kayu)
            #print("api", api)
            #print("tanah", tanah)
            #print("logam", logam)
            #print("air", air)

            #5 - Tubuh Kuat/Lemah
            kek_tub = 0
            DM = bz_elm[1]
            #print ("DM", DM)

            #musim
            #heavenly stems
            wood_h = ({"Jia", "Yi"})
            fire_h = ({"Bing", "Ding"})
            metal_h = ({"Geng", "Xin"})
            water_h = ({"Ren", "Gui"})
            earth_h = ({"Wu", "Ji"})

            #earthly branches
            spring = ({"Yin", "Mao", "Chen"})
            summer = ({"Si", "Uu", "Wei"})
            autumn = ({"Shen","You", "Xu"})
            winter = ({"Hai", "Zi", "Chou"})

            if bz_kar[6] in spring:
                lahir = "musim semi"
            elif bz_kar[6] in summer:
                lahir = "musim panas"
            elif bz_kar[6] in autumn:
                lahir = "musim gugur"
            elif bz_kar[6] in winter:
                lahir = "musim dingin"
            else: lahir=""

            if bz_kar[1] in wood_h and (bz_kar[6] in spring or bz_kar[6] in winter):
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +2
            elif bz_kar[1] in fire_h and (bz_kar[6] in summer or bz_kar[6] in spring):
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +2
            elif bz_kar[1] in metal_h and (bz_kar[6] in autumn):
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +2
            elif bz_kar[1] in water_h and (bz_kar[6] in winter or bz_kar[6] in autumn):
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +2
            elif bz_kar[1] in earth_h and bz_kar[6] == "wei":
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +2
            elif bz_kar[1] in earth_h and bz_kar[6] in transitional:
                #print("Tubuh kuat secara musim.")
                kek_tub = kek_tub +1
            else:
                print("Tubuh kurang kuat secara musim.")
            #/musim

            #DM & Resource
            if DM == "kayu" and kayu > 1:
                #print("Tubuh kuat secara elemen DM.")
                kek_tub = kek_tub +1
                #print("friend", kayu-1)
                Resc = "air"
            elif DM == "api" and api > 1:
                #print("Tubuh kuat secara elemen DM.")
                kek_tub = kek_tub +1
                #print("friend", api-1)
                Resc = "kayu"
            elif DM == "tanah" and tanah > 1:
                #print("Tubuh kuat secara elemen DM.")
                kek_tub = kek_tub +1
                #print("friend", tanah-1)
                Resc = "api"
            elif DM == "logam" and logam > 1:

bazireader/apps/contact/views.py

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail

from bazireader import settings

from .forms import ContactForm

def contact(request: HttpRequest) -> HttpResponse:

    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            send_mail("someone sent an email", message, email, [settings.DEFAULT_FROM_EMAIL])
            return render(request, "contact.html", {"form": form, "success": True })
    else:
        raise NotImplementedError

    return render(request, "contact.html", {"form": form} )

bazireader/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
#from django.template import loader

from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "index.html")
    #template = loader.get_template('index.html')
    #return HttpResponse(template.render({}, request))

def about(request: HttpRequest) -> HttpResponse:
    return render(request, "about.html")

def contact(request: HttpRequest) -> HttpResponse:
    return render(request, "contact.html")

class ProfileView(LoginRequiredMixin,TemplateView):
    template_name = "accounts/profile.html"

bazireader/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock  %}

{% block content %}
<section class="page-section" id="contact">
   <div class="container">
      <!-- Contact section heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-@"> Bazi Reader</h2>
      <!-- Icon divider -->
      <div class="divider-custom">
         <div class="divider-custom-line"></div>
         <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
         <div class="divider-custom-line"></div>
      </div>

      <div class="text-center text-secondary mb-@">
         <p>
            This is about me!
         </p>
         <p>
            You can also send us email at <a href="mailto:bazireader16@gmail.com">bazireader16@gmail.com</a>
         </p>
      </div>

      <!-- Contact section form -->
      <div class="row">
         <div class="col-lg-8 mx-auto">

            <div class="alert alert-success" role="alert">
               Under construction
            </div>

         </div>
      </div>
   </div>
</section>

{% endblock  %}

bazireader/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <style>

        .container {
          position: relative;
          text-align: center;
          color: black;
          /* text-size */
        } /* apply to all text on image */

        .top-left {
          position: absolute;
          top: 35%; /* padding */
          left: 15%; /* padding */
        }

        .top-right {
          position: absolute;
          top: 35%; /* padding */
          right: 15%; /* padding */
        }

        .top {
          position: absolute;
          top: 10%; /* padding */
          right: 47.5%; /* padding */
        }

        .bottom-left {
          position: absolute;
          bottom: 16%; /* padding */
          left: 27.5%; /* padding */
        }


        .bottom-right {
          position: absolute;
          bottom: 17%; /* padding */
          right: 27%; /* padding */
        }

        /* transform: translate(-50%, -50%); */


        </style>


        <title>{% block title %} {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />

</head>
<body>
    {% include 'navbar.html' %}

    <main id="main">
        {% block content%}
        {% endblock %}
    </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at   https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->

</body>
</html>

bazireader/templates/contact.html
{% extends 'base.html' %}

{% block title %}
   Contact
{% endblock  %}

{% block content %}
<section class="page-section" id="contact">
   <div class="container">
      <!-- Contact section heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-@"> Contact Us</h2>
      <!-- Icon divider -->
      <div class="divider-custom">
         <div class="divider-custom-line"></div>
         <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
         <div class="divider-custom-line"></div>
      </div>

      <div class="text-center text-secondary mb-@">
         <p>
            We do our best to respond to emails, but we get so many that it's hard to respond to all
         </p>
         <p>
            You can also send us email at <a href="mailto:bazireader16@gmail.com">bazireader16@gmail.com</a>
         </p>
      </div>

      <!-- Contact section form -->
      <div class="row">
         <div class="col-lg-8 mx-auto">

            {% if success %}
            <div class="alert alert-success" role="alert">
               Your message was sent! Thank you
            </div>
            {% endif %}

            <!-- to configure contact form email goto mail/contact.php -->
            <form id="contactform" name="sentMessage" novalidate="novalidate" method="post">
               {% csrf_token %}

               {% if form.non_field_errors %}
               <div class="alert alert-danger" role="alert">
                  {{ form.non_field_errors }}
               </div>
               {% endif %}

               {% for field in form %}
                <div class="control-group">
                  <div class="form-group floating-label-form-group controls mb-@ pb-2">
                     {{ field.label_tag }}
                     {{ field }}

                     {% for error in field.errors %}
                     <p class="help-block text-danger">{{ error }}</p>
                     {% endfor %}
                  </div>
               </div>
               {% endfor %}

               <br />
               <div class="form-group">
                  <button  id="sendMessageButton" type="submit">SEND</button>

               </div>
            </form>
         </div>
      </div>
   </div>
</section>

{% endblock  %}

bazireader/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Home {% endblock  %}

{% block content %}
<section class="page-section" id="contact">
   <div class="container">
      <!-- Contact section heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-@"> Bazi Reader</h2>
      <!-- Icon divider -->
      <div class="divider-custom">
         <div class="divider-custom-line"></div>
         <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
         <div class="divider-custom-line"></div>
      </div>

      <div class="text-center text-secondary mb-@">
         <p>
            Please input your name, date of birth (including hour), 8 bazi characters, and the first 2 luck periods!
         </p>
         <p>
            You can also send us email at <a href="mailto:bazireader16@gmail.com">bazireader16@gmail.com</a>
         </p>
      </div>

   </div>
</section>

{% endblock  %}

bazireader/templates/navbar.html
<!--
<div>
  {% url 'public:index' as index_url %}
  <span>
    {% if request.path == index_url %} Home {% else %}
      <a href="{{ index_url }}">Home </a>
    {% endif %}
  </span>

  {% url 'public:about' as about_url %}
  <span>
    {% if request.path == about_url %} About {% else %}
      <a href="{{ about_url }}"> About </a>
    {% endif %}
  </span>

  {% url 'contact:contact' as contact_url %}
  <span>
    {% if request.path == contact_url %} Contact {% else %}
      <a href="{{ contact_url }}"> Contact </a>
    {% endif %}
  </span>

  <span style="float:right">
    {% if user.is_authenticated %}
      {% url 'profile' as profile_url %}
        <span>Hi {% if request.path == profile_url %} {{user.username}} {% else %} <a href="{{profile_url }}"> {{user.username}} </a> {% endif %}!</span>
        <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
    {% else %}
        <span><a href="{% url 'accounts:login' %}">Login</a></span>
    {% endif %}
  </span>
</div>
-->

 <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Bazi Reader</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% url 'public:index' as index_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ index_url }}">Home</a></li>
                        {% url 'public:about' as about_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ about_url }}">About</a></li>
                        {% url 'accounts:accounts' as account_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ account_url }}">Account</a></li>
                        {% url 'contact:contact' as contact_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{{ contact_url }}">Contact</a></li>
                        {% if user.is_authenticated %}
                            {% url 'accounts:profile' as profile_url %}
                            <span> {% if request.path == profile_url %} {{user.username}} {% else %} <a href="{{ profile_url }}"> {{ user.username }} </a> {% endif %}&nbsp;&nbsp; </span>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
 </nav>